=@component('mail::message')
# 📊 Daily Activity Report
**Date:** {{ now()->format('F j, Y') }}

---

## 👥 New Users
@if ($todayUsers->isNotEmpty())
@component('mail::table')
| Name | Email | Joined At |
|:-----|:------|:----------|
@foreach ($todayUsers as $user)
| **{{ $user->name }}** | {{ $user->email }} | {{ $user->created_at->format('H:i') }} |
@endforeach
@endcomponent
@else
_No new users today._
@endif

---

## 📝 New Posts
@if ($todayPosts->isNotEmpty())
@component('mail::table')
| Title | Author | Time |
|:------|:-------|:-----|
@foreach ($todayPosts as $post)
| **{{ $post->title }}** | {{ $post->user->name }} | {{ $post->created_at->format('H:i') }} |
@endforeach
@endcomponent
@else
_No new posts today._
@endif


@component('mail::panel')
This is an automated daily summary generated by **Your App**.
@endcomponent

Thanks,
**Your App Team**
@endcomponent
